environment = QA
browser = Chrome
headless=false
Screenshot = true
implicitWait=10
explicitWait=20
ApplicationURL = https://parabank.parasoft.com/
gridUrl = http://localhost:4444/wd/hub
#ApplicationURL = https://fast.com/
